/* Generated By:JJTree: Do not edit this line. ASTa_PLUS_OP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTa_PLUS_OP extends SimpleNode {
  public ASTa_PLUS_OP(int id) {
    super(id);
  }

  public ASTa_PLUS_OP(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=59062f27737b79f3348be07d12c4bdef (do not edit this line) */
