/* Generated By:JJTree: Do not edit this line. ASTAndOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAndOp extends SimpleNode {
  public ASTAndOp(int id) {
    super(id);
  }

  public ASTAndOp(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f5a79daf9e59a5d58f3c5bf376cf191a (do not edit this line) */
