/* Generated By:JJTree: Do not edit this line. ASTa_SUBTRACT_OP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTa_SUBTRACT_OP extends SimpleNode {
  public ASTa_SUBTRACT_OP(int id) {
    super(id);
  }

  public ASTa_SUBTRACT_OP(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e5ef4c4f418680e1a06ad9b854eaeb5f (do not edit this line) */
