/* Generated By:JJTree: Do not edit this line. ASTb_SUBTRACT_OP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTb_SUBTRACT_OP extends SimpleNode {
  public ASTb_SUBTRACT_OP(int id) {
    super(id);
  }

  public ASTb_SUBTRACT_OP(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f90360d72ad7486983501a9333c54364 (do not edit this line) */
