/* Generated By:JJTree: Do not edit this line. ASTBIN_OP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBIN_OP extends SimpleNode {
  public ASTBIN_OP(int id) {
    super(id);
  }

  public ASTBIN_OP(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c164e71540235b8d4dc5a8d4d6854462 (do not edit this line) */
