/* Generated By:JJTree: Do not edit this line. ASTb_PLUS_OP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTb_PLUS_OP extends SimpleNode {
  public ASTb_PLUS_OP(int id) {
    super(id);
  }

  public ASTb_PLUS_OP(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=acfec4b6fc044b2e7c951969973e47a6 (do not edit this line) */
