/* Generated By:JJTree: Do not edit this line. ASTconstant_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconstant_decl extends SimpleNode {
  public ASTconstant_decl(int id) {
    super(id);
  }

  public ASTconstant_decl(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=daccff2de73091a886eb05e657b123ec (do not edit this line) */
