/* Generated By:JJTree: Do not edit this line. ASTCondPrime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCondPrime extends SimpleNode {
  public ASTCondPrime(int id) {
    super(id);
  }

  public ASTCondPrime(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=88ed8cf500abcb22c7198ec2f3eb3fad (do not edit this line) */
