/* Generated By:JJTree: Do not edit this line. ASTDecl_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDecl_list extends SimpleNode {
  public ASTDecl_list(int id) {
    super(id);
  }

  public ASTDecl_list(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b785063d8b0f7a19ec52e1e1981046b (do not edit this line) */
