/* Generated By:JJTree: Do not edit this line. ASTEQ_LESS_THAN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEQ_LESS_THAN extends SimpleNode {
  public ASTEQ_LESS_THAN(int id) {
    super(id);
  }

  public ASTEQ_LESS_THAN(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9c889f1efa7904e24da07b8e3e123597 (do not edit this line) */
