/* Generated By:JJTree: Do not edit this line. ASTEQ_GREATER_THAN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEQ_GREATER_THAN extends SimpleNode {
  public ASTEQ_GREATER_THAN(int id) {
    super(id);
  }

  public ASTEQ_GREATER_THAN(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dea7e687ec12cc97377dcd8b3c3a18f2 (do not edit this line) */
