/* Generated By:JJTree: Do not edit this line. ASTELSE_CODE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTELSE_CODE extends SimpleNode {
  public ASTELSE_CODE(int id) {
    super(id);
  }

  public ASTELSE_CODE(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c15a96a609423a1fd715fff5167279b9 (do not edit this line) */
