/* Generated By:JJTree: Do not edit this line. ASTFunc_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunc_list extends SimpleNode {
  public ASTFunc_list(int id) {
    super(id);
  }

  public ASTFunc_list(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=671e6a1c4b955b4ebb36d10ae155856a (do not edit this line) */
