/* Generated By:JJTree: Do not edit this line. ASTFrag.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFrag extends SimpleNode {
  public ASTFrag(int id) {
    super(id);
  }

  public ASTFrag(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a1bbdf42a3ada8d5cd2e5afb9a1d9ce2 (do not edit this line) */
