/* Generated By:JJTree: Do not edit this line. ASTFUNCTION_CODE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFUNCTION_CODE extends SimpleNode {
  public ASTFUNCTION_CODE(int id) {
    super(id);
  }

  public ASTFUNCTION_CODE(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=04c0a4d8c989f841a749cc04b4e5a1dc (do not edit this line) */
