/* Generated By:JJTree: Do not edit this line. ASTFUNC_CALL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFUNC_CALL extends SimpleNode {
  public ASTFUNC_CALL(int id) {
    super(id);
  }

  public ASTFUNC_CALL(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fbcfaf27cc7c052d14bc957dbcbd4c8e (do not edit this line) */
