/* Generated By:JJTree: Do not edit this line. ASTGREATER_THAN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGREATER_THAN extends SimpleNode {
  public ASTGREATER_THAN(int id) {
    super(id);
  }

  public ASTGREATER_THAN(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=61cf3f5853b468fbab2cc003980b1064 (do not edit this line) */
