/* Generated By:JJTree: Do not edit this line. ASTGtEqOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGtEqOp extends SimpleNode {
  public ASTGtEqOp(int id) {
    super(id);
  }

  public ASTGtEqOp(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1b6e8a0dfdba234f33dc9d59c2671aee (do not edit this line) */
