/* Generated By:JJTree: Do not edit this line. ASTIS_FALSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIS_FALSE extends SimpleNode {
  public ASTIS_FALSE(int id) {
    super(id);
  }

  public ASTIS_FALSE(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4745770c482fa29a7ca54344260b22da (do not edit this line) */
