/* Generated By:JJTree: Do not edit this line. ASTIF_CODE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF_CODE extends SimpleNode {
  public ASTIF_CODE(int id) {
    super(id);
  }

  public ASTIF_CODE(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8eee7d8bf5911a2e51b1c8e598dad8f4 (do not edit this line) */
