/* Generated By:JJTree: Do not edit this line. ASTIF_BODY.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF_BODY extends SimpleNode {
  public ASTIF_BODY(int id) {
    super(id);
  }

  public ASTIF_BODY(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dbf41c4a315610c25312927ac536beae (do not edit this line) */
