/* Generated By:JJTree: Do not edit this line. ASTIF_CONDITION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF_CONDITION extends SimpleNode {
  public ASTIF_CONDITION(int id) {
    super(id);
  }

  public ASTIF_CONDITION(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=180df1cf205929c9d86e33ae2b3616d3 (do not edit this line) */
