/* Generated By:JJTree: Do not edit this line. ASTIS_TRUE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIS_TRUE extends SimpleNode {
  public ASTIS_TRUE(int id) {
    super(id);
  }

  public ASTIS_TRUE(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7f79dcfe253f801d295d3850801c1fe8 (do not edit this line) */
