/* Generated By:JJTree: Do not edit this line. ASTLESS_THAN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLESS_THAN extends SimpleNode {
  public ASTLESS_THAN(int id) {
    super(id);
  }

  public ASTLESS_THAN(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=127ca7271be0def2e6b9c9060f1edeba (do not edit this line) */
