/* Generated By:JJTree: Do not edit this line. ASTMAIN_DECLS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMAIN_DECLS extends SimpleNode {
  public ASTMAIN_DECLS(int id) {
    super(id);
  }

  public ASTMAIN_DECLS(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b368d8a01bece750310e338310bbe78f (do not edit this line) */
