/* Generated By:JJTree: Do not edit this line. ASTMAIN_CODE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMAIN_CODE extends SimpleNode {
  public ASTMAIN_CODE(int id) {
    super(id);
  }

  public ASTMAIN_CODE(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=46cbaa32ac283603fa8f4ce6b1cfded3 (do not edit this line) */
