/* Generated By:JJTree: Do not edit this line. ASTMain_Code.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMain_Code extends SimpleNode {
  public ASTMain_Code(int id) {
    super(id);
  }

  public ASTMain_Code(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d069684f43fa9952a0af6656b5ec1ba0 (do not edit this line) */
