/* Generated By:JJTree: Do not edit this line. ASTNEG_ID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEG_ID extends SimpleNode {
  public ASTNEG_ID(int id) {
    super(id);
  }

  public ASTNEG_ID(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9d8c7c724d8bb9a7b3c563affd585785 (do not edit this line) */
