/* Generated By:JJTree: Do not edit this line. ASTNempParamListPrime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNempParamListPrime extends SimpleNode {
  public ASTNempParamListPrime(int id) {
    super(id);
  }

  public ASTNempParamListPrime(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d97a766c8fc0050a446d3868d25f7f9e (do not edit this line) */
