/* Generated By:JJTree: Do not edit this line. ASTNEG_EQUALS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEG_EQUALS extends SimpleNode {
  public ASTNEG_EQUALS(int id) {
    super(id);
  }

  public ASTNEG_EQUALS(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0aa8e7ebf9f1e5e4f678e88e7f354d5f (do not edit this line) */
