/* Generated By:JJTree: Do not edit this line. ASTNEGATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEGATION extends SimpleNode {
  public ASTNEGATION(int id) {
    super(id);
  }

  public ASTNEGATION(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b262a8e88964f5ffc3e0ebec640988de (do not edit this line) */
