/* Generated By:JJTree: Do not edit this line. ASTnemp_arg_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnemp_arg_list extends SimpleNode {
  public ASTnemp_arg_list(int id) {
    super(id);
  }

  public ASTnemp_arg_list(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=de1fdf4a14f45369314f368e9f33582f (do not edit this line) */
