/* Generated By:JJTree: Do not edit this line. ASTNOT_EQUAL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNOT_EQUAL extends SimpleNode {
  public ASTNOT_EQUAL(int id) {
    super(id);
  }

  public ASTNOT_EQUAL(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a1e977df9dc25577dba74249f612be9b (do not edit this line) */
