/* Generated By:JJTree: Do not edit this line. ASTNempParamList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNempParamList extends SimpleNode {
  public ASTNempParamList(int id) {
    super(id);
  }

  public ASTNempParamList(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f7ee77df996fb24c2392b018a50d4b92 (do not edit this line) */
