/* Generated By:JJTree: Do not edit this line. ASTNempArgList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNempArgList extends SimpleNode {
  public ASTNempArgList(int id) {
    super(id);
  }

  public ASTNempArgList(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6287eef4b535bf58e08a57ae38dabef5 (do not edit this line) */
