/* Generated By:JJTree: Do not edit this line. ASTProg_Start.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTProg_Start extends SimpleNode {
  public ASTProg_Start(int id) {
    super(id);
  }

  public ASTProg_Start(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=83ac7025176ea44b6e95c4c7e7bad3a3 (do not edit this line) */
