/* Generated By:JJTree: Do not edit this line. ASTPARAM_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPARAM_LIST extends SimpleNode {
  public ASTPARAM_LIST(int id) {
    super(id);
  }

  public ASTPARAM_LIST(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b4a890c9226489d73ea3f365630c38fe (do not edit this line) */
