/* Generated By:JJTree: Do not edit this line. ASTSUBTRACT_OP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSUBTRACT_OP extends SimpleNode {
  public ASTSUBTRACT_OP(int id) {
    super(id);
  }

  public ASTSUBTRACT_OP(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bfee8f9d50283bbf81bdc0710b196e64 (do not edit this line) */
