/* Generated By:JJTree: Do not edit this line. ASTstatement_block.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatement_block extends SimpleNode {
  public ASTstatement_block(int id) {
    super(id);
  }

  public ASTstatement_block(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=23557ba12b5c444e808ea8fb2c7e5e6c (do not edit this line) */
