/* Generated By:JJTree: Do not edit this line. ASTSTATEMENT_BLOCK.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATEMENT_BLOCK extends SimpleNode {
  public ASTSTATEMENT_BLOCK(int id) {
    super(id);
  }

  public ASTSTATEMENT_BLOCK(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6fd82181195b241104c9a16df6428efa (do not edit this line) */
