/* Generated By:JJTree: Do not edit this line. ASTVAL_TYPE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVAL_TYPE extends SimpleNode {
  public ASTVAL_TYPE(int id) {
    super(id);
  }

  public ASTVAL_TYPE(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3f118f43dc1c636313f9807f0fe4b39e (do not edit this line) */
