/* Generated By:JJTree: Do not edit this line. ASTvariable_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvariable_decl extends SimpleNode {
  public ASTvariable_decl(int id) {
    super(id);
  }

  public ASTvariable_decl(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=45adff65be1ef4b2c8507d1a821fff0e (do not edit this line) */
