/* Generated By:JJTree: Do not edit this line. ASTWHILE_CONDITION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWHILE_CONDITION extends SimpleNode {
  public ASTWHILE_CONDITION(int id) {
    super(id);
  }

  public ASTWHILE_CONDITION(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eace3af89325accf42f493403445da9a (do not edit this line) */
