/* Generated By:JJTree: Do not edit this line. ASTWHILE_CODE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWHILE_CODE extends SimpleNode {
  public ASTWHILE_CODE(int id) {
    super(id);
  }

  public ASTWHILE_CODE(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=836b19db352a9f6a56e7cae21a40a53e (do not edit this line) */
