/* Generated By:JavaCC: Do not edit this line. MyParserVisitor.java Version 5.0 */
public interface MyParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTDECL_LIST node, Object data);
  public Object visit(ASTvar_decl node, Object data);
  public Object visit(ASTconst_decl node, Object data);
  public Object visit(ASTInt node, Object data);
  public Object visit(ASTBool node, Object data);
  public Object visit(ASTFunc_list node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTParam node, Object data);
  public Object visit(ASTmain node, Object data);
  public Object visit(ASTstatement_block node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTbinary_arith_op node, Object data);
  public Object visit(ASTcondition node, Object data);
  public Object visit(ASTcomp_op node, Object data);
  public Object visit(ASTarg_list node, Object data);
  public Object visit(ASTnemp_arg_list node, Object data);
}
/* JavaCC - OriginalChecksum=6ca3bcbcf9d7d3365f75c83be28a4afa (do not edit this line) */
