/* Generated By:JavaCC: Do not edit this line. MyParserTreeConstants.java Version 5.0 */
public interface MyParserTreeConstants
{
  public int JJTPROG_START = 0;
  public int JJTVOID = 1;
  public int JJTDECL_LIST = 2;
  public int JJTVAR_DECL = 3;
  public int JJTCONST_DECL = 4;
  public int JJTINT = 5;
  public int JJTBOOL = 6;
  public int JJTFUNCTION = 7;
  public int JJTPARAM = 8;
  public int JJTMAIN_CODE = 9;
  public int JJTASSIGN_OP = 10;
  public int JJTIF = 11;
  public int JJTELSE = 12;
  public int JJTWHILE = 13;
  public int JJTEXPRESSION = 14;
  public int JJTPLUS_OP = 15;
  public int JJTSUBTRACT_OP = 16;
  public int JJTCONDITION = 17;
  public int JJTLIST_OF_ARGS = 18;
  public int JJTID = 19;


  public String[] jjtNodeName = {
    "Prog_Start",
    "void",
    "Decl_list",
    "var_decl",
    "const_decl",
    "Int",
    "Bool",
    "Function",
    "Param",
    "Main_Code",
    "ASSIGN_OP",
    "IF",
    "ELSE",
    "WHILE",
    "expression",
    "PLUS_OP",
    "SUBTRACT_OP",
    "condition",
    "list_of_args",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=ead86f0dd0de178b2aabb9e982553fa1 (do not edit this line) */
