/* Generated By:JavaCC: Do not edit this line. MyParserVisitor.java Version 5.0 */
public interface MyParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTDECL_LIST node, Object data);
  public Object visit(ASTvar_decl node, Object data);
  public Object visit(ASTconst_decl node, Object data);
  public Object visit(ASTInt node, Object data);
  public Object visit(ASTBool node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTParam node, Object data);
  public Object visit(ASTMain node, Object data);
  public Object visit(ASTASSIGN_OP node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTcondition node, Object data);
  public Object visit(ASTarg_list node, Object data);
  public Object visit(ASTID node, Object data);
}
/* JavaCC - OriginalChecksum=4cb841e88e333520343776111f59a687 (do not edit this line) */
