/* Generated By:JavaCC: Do not edit this line. MyParserTreeConstants.java Version 5.0 */
public interface MyParserTreeConstants
{
  public int JJTPROG_START = 0;
  public int JJTVOID = 1;
  public int JJTVARIABLE_DECL = 2;
  public int JJTCONSTANT_DECL = 3;
  public int JJTVAL_TYPE = 4;
  public int JJTFUNCTION = 5;
  public int JJTPARAM_LIST = 6;
  public int JJTDECL_LIST = 7;
  public int JJTFUNCTION_CODE = 8;
  public int JJTRETURNS = 9;
  public int JJTPARAMETER = 10;
  public int JJTMAIN = 11;
  public int JJTMAIN_DECLS = 12;
  public int JJTMAIN_CODE = 13;
  public int JJTASSIGN_OP = 14;
  public int JJTFUNC_CALL = 15;
  public int JJTIF_CONDITION = 16;
  public int JJTIF_CODE = 17;
  public int JJTIF = 18;
  public int JJTELSE_CODE = 19;
  public int JJTELSE = 20;
  public int JJTWHILE_CONDITION = 21;
  public int JJTWHILE_CODE = 22;
  public int JJTWHILE = 23;
  public int JJTSKIP = 24;
  public int JJTPLUS_OP = 25;
  public int JJTSUBTRACT_OP = 26;
  public int JJTNEGATION = 27;
  public int JJTEQUAL = 28;
  public int JJTNOT_EQUAL = 29;
  public int JJTLESS_THAN = 30;
  public int JJTEQ_LESS_THAN = 31;
  public int JJTGREATER_THAN = 32;
  public int JJTEQ_GREATER_THAN = 33;
  public int JJTOR = 34;
  public int JJTAND = 35;
  public int JJTARG_LIST = 36;
  public int JJTID = 37;
  public int JJTINT = 38;
  public int JJTIS_TRUE = 39;
  public int JJTIS_FALSE = 40;


  public String[] jjtNodeName = {
    "Prog_Start",
    "void",
    "variable_decl",
    "constant_decl",
    "VAL_TYPE",
    "Function",
    "PARAM_LIST",
    "DECL_LIST",
    "FUNCTION_CODE",
    "RETURNS",
    "Parameter",
    "MAIN",
    "MAIN_DECLS",
    "MAIN_CODE",
    "ASSIGN_OP",
    "FUNC_CALL",
    "IF_CONDITION",
    "IF_CODE",
    "IF",
    "ELSE_CODE",
    "ELSE",
    "WHILE_CONDITION",
    "WHILE_CODE",
    "WHILE",
    "SKIP",
    "PLUS_OP",
    "SUBTRACT_OP",
    "NEGATION",
    "EQUAL",
    "NOT_EQUAL",
    "LESS_THAN",
    "EQ_LESS_THAN",
    "GREATER_THAN",
    "EQ_GREATER_THAN",
    "OR",
    "AND",
    "ARG_LIST",
    "ID",
    "INT",
    "IS_TRUE",
    "IS_FALSE",
  };
}
/* JavaCC - OriginalChecksum=5ba2594529b72c05612fc5afbd41e6ff (do not edit this line) */
