/* Generated By:JavaCC: Do not edit this line. MyParserVisitor.java Version 5.0 */
public interface MyParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProg_Start node, Object data);
  public Object visit(ASTDecl_list node, Object data);
  public Object visit(ASTvariable_decl node, Object data);
  public Object visit(ASTconstant_decl node, Object data);
  public Object visit(ASTVAL_TYPE node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTParameter node, Object data);
  public Object visit(ASTMain_Code node, Object data);
  public Object visit(ASTASSIGN_OP node, Object data);
  public Object visit(ASTIF node, Object data);
  public Object visit(ASTELSE node, Object data);
  public Object visit(ASTWHILE node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTPLUS_OP node, Object data);
  public Object visit(ASTSUBTRACT_OP node, Object data);
  public Object visit(ASTcondition node, Object data);
  public Object visit(ASTlist_of_args node, Object data);
  public Object visit(ASTID node, Object data);
}
/* JavaCC - OriginalChecksum=0d6f90575daa2fc1d03d7ee76ed29e4b (do not edit this line) */
