/* Generated By:JavaCC: Do not edit this line. MyParserTreeConstants.java Version 5.0 */
public interface MyParserTreeConstants
{
  public int JJTPROG_START = 0;
  public int JJTVOID = 1;
  public int JJTDECL_LIST = 2;
  public int JJTVARIABLE_DECL = 3;
  public int JJTCONSTANT_DECL = 4;
  public int JJTVAL_TYPE = 5;
  public int JJTFUNCTION = 6;
  public int JJTPARAMETER = 7;
  public int JJTMAIN_CODE = 8;
  public int JJTIF = 9;
  public int JJTELSE = 10;
  public int JJTWHILE = 11;
  public int JJTA_PLUS_OP = 12;
  public int JJTA_SUBTRACT_OP = 13;
  public int JJTB_SUBTRACT_OP = 14;
  public int JJTB_PLUS_OP = 15;
  public int JJTPLUS_OP = 16;
  public int JJTSUBTRACT_OP = 17;
  public int JJTCONDITION = 18;
  public int JJTLIST_OF_ARGS = 19;
  public int JJTID = 20;
  public int JJTINT = 21;
  public int JJTIS_TRUE = 22;
  public int JJTIS_FALSE = 23;


  public String[] jjtNodeName = {
    "Prog_Start",
    "void",
    "Decl_list",
    "variable_decl",
    "constant_decl",
    "VAL_TYPE",
    "Function",
    "Parameter",
    "Main_Code",
    "IF",
    "ELSE",
    "WHILE",
    "a_PLUS_OP",
    "a_SUBTRACT_OP",
    "b_SUBTRACT_OP",
    "b_PLUS_OP",
    "PLUS_OP",
    "SUBTRACT_OP",
    "condition",
    "list_of_args",
    "ID",
    "INT",
    "IS_TRUE",
    "IS_FALSE",
  };
}
/* JavaCC - OriginalChecksum=277f5565c1c67232d6dd780caab82d2b (do not edit this line) */
